In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline
#dftrain=pd.read_csv("/Users/leenavig/Documents/SImplilearn Live class/Dataset for the project/train 2.csv")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
dftrain=pd.read_csv("/content/drive/MyDrive/PROJECTS_simplilearn/Mercedes_benz_train.csv")

In [4]:
dftrain.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [5]:
dftest=pd.read_csv("/content/drive/MyDrive/PROJECTS_simplilearn/mercedes_benz_test.csv")

In [6]:
dftrain.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [7]:
dftrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [8]:
# to obtain the column heads and the number of unique entries/labels in each column 
dftrain.columns


Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [9]:
dftest.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [10]:
for col in dftrain:
    print(col, ";", len(dftrain[col].unique()),'labels')

ID ; 4209 labels
y ; 2545 labels
X0 ; 47 labels
X1 ; 27 labels
X2 ; 44 labels
X3 ; 7 labels
X4 ; 4 labels
X5 ; 29 labels
X6 ; 12 labels
X8 ; 25 labels
X10 ; 2 labels
X11 ; 1 labels
X12 ; 2 labels
X13 ; 2 labels
X14 ; 2 labels
X15 ; 2 labels
X16 ; 2 labels
X17 ; 2 labels
X18 ; 2 labels
X19 ; 2 labels
X20 ; 2 labels
X21 ; 2 labels
X22 ; 2 labels
X23 ; 2 labels
X24 ; 2 labels
X26 ; 2 labels
X27 ; 2 labels
X28 ; 2 labels
X29 ; 2 labels
X30 ; 2 labels
X31 ; 2 labels
X32 ; 2 labels
X33 ; 2 labels
X34 ; 2 labels
X35 ; 2 labels
X36 ; 2 labels
X37 ; 2 labels
X38 ; 2 labels
X39 ; 2 labels
X40 ; 2 labels
X41 ; 2 labels
X42 ; 2 labels
X43 ; 2 labels
X44 ; 2 labels
X45 ; 2 labels
X46 ; 2 labels
X47 ; 2 labels
X48 ; 2 labels
X49 ; 2 labels
X50 ; 2 labels
X51 ; 2 labels
X52 ; 2 labels
X53 ; 2 labels
X54 ; 2 labels
X55 ; 2 labels
X56 ; 2 labels
X57 ; 2 labels
X58 ; 2 labels
X59 ; 2 labels
X60 ; 2 labels
X61 ; 2 labels
X62 ; 2 labels
X63 ; 2 labels
X64 ; 2 labels
X65 ; 2 labels
X66 ; 2 labels
X67 ; 2 l

In [11]:
dftrain.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [12]:
# to drop the columns with minimum variance
single=[]
#print(dftrain.columns)
#print(len(dftrain[[columns=1).unique()))
for col in dftrain.columns:
    if len(dftrain[col].unique())==1:
        single.append(col)
    
dftrain.drop(columns=single,inplace=True)  
dftest.drop(columns=single,inplace=True)

In [13]:
dftrain.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=366)

In [14]:
dftest.columns


Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=365)

In [15]:
# to drop the columns with minimum variance
single=[]
#print(dftrain.columns)
#print(len(dftrain[[columns=1).unique()))
for col in dftrain.columns:
    if len(dftrain[col].unique())==1:
        single.append(col)
    
dftrain.drop(columns=single,inplace=True)  
dftest.drop(columns=single,inplace=True)  

In [16]:
dftrain.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=366)

In [17]:
dftest.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=365)

In [18]:
dftrain.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 366 columns]

In [19]:
# Label Encoding the data
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

In [20]:
newdf=dftrain.apply(le.fit_transform)
newtest=dftest.apply(le.fit_transform)

In [21]:
newdf.shape,newtest.shape

((4209, 366), (4209, 365))

In [22]:
x_train=newdf.drop(['y'],axis=1)


In [23]:
x_train.shape,newtest.shape


((4209, 365), (4209, 365))

In [24]:
# Performing Principal Componenet Analysis on the label encoded data for dimentionality reduction
from sklearn.decomposition import PCA

In [25]:
sklearn_pca=PCA(n_components=10)
output_pca=sklearn_pca.fit_transform(x_train)
output_pca

array([[-2.10392518e+03,  8.62388945e-01, -1.84271114e-01, ...,
         4.09573528e+00,  1.64375030e+00, -4.97578397e-01],
       [-2.10290920e+03,  7.84932754e-01,  1.62709020e+00, ...,
        -4.83073882e-01,  9.24947609e-01, -6.21397870e-01],
       [-2.10191260e+03,  1.64356376e+01,  1.23258860e+01, ...,
         1.13266637e+00,  1.69341856e+00, -4.31051745e-01],
       ...,
       [ 2.10192644e+03,  2.87670119e+01,  1.49202369e+01, ...,
         3.10789269e+00, -3.54895683e-01,  1.06162321e-01],
       [ 2.10292655e+03,  2.27279761e+01,  1.72985538e+00, ...,
        -2.99735277e+00,  1.60511143e+00,  2.07246748e+00],
       [ 2.10392601e+03, -1.75454605e+01, -9.82681801e+00, ...,
         9.55184379e-01,  6.90365267e-01,  6.35631892e-01]])

In [26]:
test_transformed = sklearn_pca.transform(newtest)

In [27]:
explained_variance=sklearn_pca.explained_variance_ratio_
explained_variance

array([9.99659608e-01, 1.38083753e-04, 7.69770342e-05, 4.40107808e-05,
       3.31849481e-05, 2.66009200e-05, 5.73061934e-06, 2.67845282e-06,
       1.56203752e-06, 1.05802559e-06])

In [28]:
# performing xgboost on label encoded and dimentionally reduced data
import xgboost as xgb
model=xgb.XGBClassifier(random_state=1, learning_rate=0.01)
model.fit(output_pca, newdf['y'])

XGBClassifier(learning_rate=0.01, objective='multi:softprob', random_state=1)

In [29]:
# making prediction on the test set.
preds=model.predict(test_transformed)

In [32]:
print (preds)

[ 810  328  569 ... 1180 1952  666]
